exec dbus-update-activation-environment --systemd --all
exec dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP=sway
exec dbus-update-activation-environment DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
exec /usr/bin/lxpolkit
exec mako &

exec awww-daemon
exec nvibrant 0 0 0 0 500
exec wlsunset -l 46.477 -L 30.732 -t 3500 -T 6600 -daemonize
exec Telegram
exec $enable_input_remapper
exec $random_wallpaper

### Idle configuration

exec swayidle -w \
  timeout 600 'swaymsg "output * power off"' \
  resume 'swaymsg "output * power on"'

# exec swayidle -w \
#   timeout 600 'swaylock --color 000000'
