bar {
    position top

    status_command $swaybar

    font pango:IosevkaTerm Nerd Font 10

    colors {
        statusline         $color7
        background         $color0CC
        inactive_workspace $color0 $color0 $color8
        focused_workspace  $color4 $color4 $color0
    }
}
