# Window blur
blur enable
blur_xray disable
blur_passes 3
blur_radius 5
blur_noise 0.02
blur_brightness 1.0
blur_contrast 1.0
blur_saturation 1.0

# Corner radius
corner_radius 8

# Window shadows
shadows disable

# LayerShell effects for swaybar
layer_effects "panel" {
    blur enable;
    blur_xray disable;
    blur_ignore_transparent enable;
}

# Dim unfocused windows
default_dim_inactive 0.10

# Misc
titlebar_separator disable
scratchpad_minimize disable
