set $mod Mod4

# Workspaces
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws0 "0"

# Colors
set $bg #222222
set $fg #d8a657
set $ur #ea6962
set $uf #a89984

# System apps
set $terminal alacritty
set $browser librewolf
set $filemanager thunar
set $menu kickoff
set $pdfreader zathura
set $audiosettings pavucontrol
set $taskmanager xfce4-taskmanager
set $idle swayidle -w timeout 1 "swaymsg 'output * power off'" resume "swaymsg 'output * power on'; pkill -nx swayidle"

# Custom scripts
set $swaybar ~/.local/scripts/swaybar_status

set $toggle_input_remapper ~/.local/scripts/toggle_input_remapper
set $toggle_mic ~/.local/scripts/toggle_mic
set $enable_input_remapper $toggle_input_remapper force

set $random_wallpaper ~/.local/scripts/random_wallpaper
set $wallpapermenu ~/.local/scripts/wallpapermenu
set $brightness ~/.local/scripts/brightness

set $full_screenshot ~/.local/scripts/screenshot_full
set $area_screenshot ~/.local/scripts/screenshot_area
