### Youtube Support

script-opts=ytdl_hook-ytdl_path=yt-dlp

# Default quality. Use uosc to change quality on the fly
ytdl-format=bestvideo[height<=?1080][fps<=?60][vcodec!=?vp9]+bestaudio/best

# Should fix 403 Forbidden error
ytdl-raw-options-append=cookies=$HOME/.config/mpv/cookies.txt

# https://unix.stackexchange.com/questions/414639/is-it-possible-to-continue-movies-from-where-one-leaves-in-mpv-as-can-be-done-in
save-position-on-quit

vo=gpu-next
gpu-api=vulkan
hwdec=nvdec
profile=high-quality

volume-max=200
sub-scale=0.8

screenshot-directory=~/Pictures/mpv_screenshots
