# Status bar options
set -g status-style "fg={foreground},bg={background}"

# Active/Inactive Windows
setw -g window-status-current-style "fg={background},bg={color4},bold"
setw -g window-status-current-format " #I:#W#F "
setw -g window-status-style "fg={foreground},bg={background}"
setw -g window-status-format " #I:#W#F "

# Pane Borders
set -g pane-border-style "fg={color8}"
set -g pane-active-border-style "fg={color4}"

# Command/Message Line
set -g message-style "fg={foreground},bg={background}"

# Copy/Selection Mode
setw -g mode-style "fg={background},bg={color3}"
