#!/usr/bin/env bash

# Ensure user binaries (~/.local/bin) are in PATH
export PATH="$HOME/.local/bin:$HOME/.local/scripts:$PATH"

WALLPAPER_DIR="$HOME/Pictures/wallpapers"
SCRIPT=~/.local/scripts/pywal16

WALLPAPER=$(
  find "$WALLPAPER_DIR" \
    -type f \
    \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \) \
    | shuf -n1
)

wal -s -i "$WALLPAPER" -o "$SCRIPT"
