#!/bin/bash

# Toggle mic mute
pactl set-source-mute @DEFAULT_SOURCE@ toggle

# Check new state
IS_MUTED=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')

# Show notification
if [ "$IS_MUTED" = "yes" ]; then
  notify-send -t 500 "Microphone" "Muted"
else
  notify-send -t 500 "Microphone" "Unmuted"
fi
