#!/usr/bin/env bash

DIRECTORY=~/Pictures/wallpapers/other
SCRIPT=~/.local/bin/pywal16

menu() {
  CHOICE=$(swayimg -g "$DIRECTORY")

  case $CHOICE in
    *.*) wal -i "$CHOICE" -o "$SCRIPT" ;;
    *) exit 0 ;;
  esac
}

case "$#" in
  0) menu ;;
  1) wal -i "$1" -o "$SCRIPT" ;;
  2) wal -i "$1" --theme "$2" -o "$SCRIPT" ;;
  *) exit 0 ;;
esac
